# Generated by Django 4.2.7 on 2024-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_last_mame_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'On way'), (3, 'Delivered')], default=0),
        ),
    ]
