# Generated by Django 4.2.7 on 2023-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_gender_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='l_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='m_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='s_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='xl_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='xs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='xxl_count',
            field=models.IntegerField(default=0),
        ),
    ]
