# Generated by Django 4.2.7 on 2023-12-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('Man', 'Male'), ('Woman', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
