# Generated by Django 4.2.7 on 2024-01-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brands',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.brands'),
            preserve_default=False,
        ),
    ]
