# Generated by Django 4.2.7 on 2024-01-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='l_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='m_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='s_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='xl_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='xs_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='xxl_count',
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
