# Generated by Django 4.2.7 on 2024-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productsize_product_remove_productsize_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
