# Generated by Django 4.2.7 on 2024-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_products_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
