# Generated by Django 4.2.7 on 2024-02-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_products_l_count_remove_products_m_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_productsize', to='products.products'),
        ),
    ]
