# Generated by Django 4.2.7 on 2024-02-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_basket_size_alter_productsize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
