# Generated by Django 4.2.7 on 2024-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_products_price'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ulubione',
            field=models.ManyToManyField(blank=True, related_name='myproducts', to='products.products'),
        ),
    ]
